apiVersion: v1
kind: BuildConfig
metadata:
  name: rhel-atomic
spec:
  triggers:
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'git@github.com:section6nz/openshift-rhel-atomic.git'
      ref: master
      contextDir: images/rhel-atomic
    sourceSecret:
      name: deployment-key
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhel-atomic:latest
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: 'rhel-atomic:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
